#!/usr/bin/python
file = list(open('song', 'r'))
if file[0] == "!" and file[0][1] == "@" and file[0][2] == "#":
	album = raw_input("what song are you listening to?")
elif file[0] != "!@#":
	album = file[0]
	f1 = open('song', 'w')
	f1.write("!@#" + '\n')
	#print(f1)
print(album)
album = album.replace(" ","+")
newurl = "https://itunes.apple.com/search?term=" + album + "&limit=1&callback=dataReceiver"
line53 = '\t<script src="' + newurl + '"></script>\n'
f = list(open('index.html','r'))
print(f[53])
f[53] = line53
f2 = open('newindex.html','w')
for line in f:
	f2.write(line)