#!/usr/bin/env bash
./gupdate
rm index.html
mv newindex.html index.html
git push origin master
expect "Username for 'https://github.com':"
send "amshr"
expect "Password for 'https://amshr@github.com':"
send "asdfghjkl;'1"
EOD
echo "yay"
